### ISSUE TITLE
Handling amount +0 in getamount method

### ISSUE THREAD

**Issue by sac8732** [kenwilcox/BankFileParsers#10]
03,1234567890,USD,010,+83150971,,,015,+83253492,,,072,+110200,,,074,+0,,/

+0 is failing in the current method.

**Comment by kenwilcox** [comment]
Interesting, I haven’t seen that yet. If you want to make this change you can update the GetAmount method in BaiFileHelpers.cs. In there I’m calling decimal.Parse. I bet it will work if you add NumberStyles.AllowLeadingSign

https://docs.microsoft.com/en-us/dotnet/api/system.globalization.numberstyles?view=net-5.0

I happily take pull requests.

**Comment by sac8732** [comment]
Fixed the code and sent PR.

   

    On Friday, 10 September, 2021, 10:07:40 pm GMT-5, Ken Wilcox ***@***.***> wrote:  
 
 


Interesting, I haven’t seen that yet. If you want to make this change you can update the GetAmount method in BaiFileHelpers.cs. In there I’m calling decimal.Parse. I bet it will work if you add NumberStyles.AllowLeadingSign

https://docs.microsoft.com/en-us/dotnet/api/system.globalization.numberstyles?view=net-5.0

I happily take pull requests.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kenwilcox** [comment]
This was fixed with PR #11
