### ISSUE TITLE
AccountFundTypeFactory Substring length error

### ISSUE THREAD

**Issue by DanielBhatti** [kenwilcox/BankFileParsers#26]
I have a BAI file with a format like this for the first few lines:
01,1,2,3,4,5,6,7,8/
02,1,2,3,4,5,USD,6/
03,1,USD/

The third line gives an issue in the AccountFundTypeFactory class.  Specifically this section, where the last line throws an index error within the Substring method:
```cs
                if (line.StartsWith("03"))
                {
                    // The first thre fields are record, account and currency
                    var fields = line.Split(',');
                    RecordCode = fields[0];
                    CustomerAccountNumber = fields[1];
                    CurrencyCode = fields[2];
                    var trailing = fields.Count() > 2? ",":"";
                    var replaced = string.Format("{0},{1},{2}{3}", fields[0], fields[1], fields[2], trailing);
                    line = line.Substring(replaced.Length);
                }
```

The error is due to the trailing comma in the `replaced` string.  Namely, `line + "," == replaced`.  Because `line` is shorter than `replaced`, this causes an error.

I believe the issue is due to the line `var trailing = fields.Count() > 2? ",":"";`, where the 2 should be a 3.

I've made the change and tested locally and am able to process the BAI file I'm using, and I was able to process other files I had too.

I'll make a PR, let me know if any issues or anything else I should address.

This exception was originally thrown at this call stack:
    string.Substring(int, int) in String.Manipulation.cs
    BankFileParsers.AccountFundTypeFactory.AccountFundTypeFactory(System.Collections.Generic.IEnumerable<string>) in AccountFundTypeFactory.cs
    BankFileParsers.Account.Account(BankFileParsers.BaiAccount, string) in Account.cs
    BankFileParsers.Group.Group(BankFileParsers.BaiGroup) in Group.cs
    BankFileParsers.TranslatedBaiFile.TranslatedBaiFile(BankFileParsers.BaiFile) in TranslatedBaiFile.cs
    BankFileParsers.BaiTranslator.Translate(BankFileParsers.BaiFile) in BaiTranslator.cs

**Comment by kenwilcox** [comment]
Interesting. I haven't seen that yet. Good catch! I'll won't be able to take a look at your PR until this weekend. I'll see if I can validate it, then push it through.

**Comment by DanielBhatti** [comment]
No problem, let me know if you need me to send a sample file.  I can scrub the current one I'm using for any testing.

**Comment by kenwilcox** [comment]
Thanks for this. Sorry for the delay. Version 0.2.2 is just awaiting verification on nuget.org
