### ISSUE TITLE
AccountFundTypeFactory bug

### ISSUE THREAD

**Issue by jedkass** [kenwilcox/BankFileParsers#6]
Hi,

First off, thank you for writing this library. I can tell it will be a huge time saver for me. 

I think I have found a bug in the AcountFundTypeFactory class, causing an ArgumentOutOfRangeException to be thrown. There is the section where you are parsing lines that start with "03":

`if (line.StartsWith("03"))`
                `{`
                    `    // The first thre fields are record, account and currency`
                    `    var fields = line.Split(',');`
                    `    RecordCode = fields[0];`
                    `    CustomerAccountNumber = fields[1];`
                    `    CurrencyCode = fields[2];`
                    `    var replaced = string.Format("{0},{1},{2},", fields[0], fields[1], fields[2]);`
                    `    line = line.Substring(replaced.Length);`
                `}`

In the line `var replaced = string.Format("{0},{1},{2},", fields[0], fields[1], fields[2]);`, you add a trailing comma in your format string. As a result, the length of the `replaced` variable is longer than the `line` variable, so the `Substring` call throws an exception. When I removed the trailing comma (locally), the call to `BaiTranslator`'s `Translate()` call successfully returned a `TranslatedBaiFile` object. 

Maybe the bank files you were looking at when writing this had information after the `CurrencyCode`, so the `Substring` call didn't throw any exception during your testing, but the ones I am looking at don't. I'm obviously not as familiar with this code so if I am missing something, please let me know. Again, thank you for this!

**Comment by kenwilcox** [comment]
Sorry for the delay. I just checked the spec and the currency code is an optional field. Your assumption is correct in that the files I've been using have that field so it wasn't something that I noticed (it's been working for 878 days without a change).

I believe I have a fix in place that should work for both scenarios. Check it out and let me know.
